// Code generated by MCHP Chatbot
#ifndef __BSP_LCD_H
#define __BSP_LCD_H

#include "fonts/fonts.h"
#include "stm32f4xx_hal.h"

#ifdef __cplusplus
extern "C" {
#endif

// ========================== LCD 基础参数配置 ==========================
#define LCD_WIDTH            800U    // 屏幕宽度
#define LCD_HEIGHT           480U    // 屏幕高度
#define LCD_PIXEL_SIZE       2U      // RGB565每个像素占2字节
#define LCD_LINE_OFFSET      0U      // 行间距（printf/字符串绘制用）
#define LCD_CHAR_SPACE       0U      // 字符间距（printf/字符串绘制用）
#define DMA2D_TIMEOUT_MS     100U    // DMA2D操作超时时间

// ========================== 图层地址定义 ==========================
#define LCD_BG_LAYER_ADDR    0xD0000000U  // 背景层基地址
#define LCD_FG_LAYER_ADDR    0xD0200000U  // 前景层基地址

// ========================== RGB565 颜色定义 ==========================
#define RGB565(r, g, b)      ((((r) & 0xF8) << 8) | (((g) & 0xFC) << 3) | ((b) >> 3))

// 常用颜色宏定义
#define COLOR_WHITE          RGB565(255, 255, 255)
#define COLOR_BLACK          RGB565(0, 0, 0)
#define COLOR_RED            RGB565(255, 0, 0)
#define COLOR_GREEN          RGB565(0, 255, 0)
#define COLOR_BLUE           RGB565(0, 0, 255)
#define COLOR_YELLOW         RGB565(255, 255, 0)
#define COLOR_CYAN           RGB565(0, 255, 255)
#define COLOR_MAGENTA        RGB565(255, 0, 255)
#define COLOR_ORANGE         RGB565(255, 165, 0)
#define COLOR_PURPLE         RGB565(128, 0, 128)
#define COLOR_PINK           RGB565(255, 192, 203)
#define COLOR_BROWN          RGB565(165, 42, 42)
#define COLOR_GRAY           RGB565(128, 128, 128)
#define COLOR_LIGHT_GRAY     RGB565(192, 192, 192)
#define COLOR_DARK_RED       RGB565(128, 0, 0)
#define COLOR_DARK_GREEN     RGB565(0, 128, 0)
#define COLOR_DARK_BLUE      RGB565(0, 0, 128)
#define COLOR_TRANSPARENT    0xFFFFU      // 透明色标记

// ========================== 枚举类型定义 ==========================
/**
 * @brief LCD图层枚举
 */
typedef enum
{
  LCD_LAYER_BG = 0,  /**< 背景层 */
  LCD_LAYER_FG = 1   /**< 前景层 */
} LCD_Layer_t;

// ========================== 结构体定义 ==========================
/**
 * @brief LCD窗口结构体（描述图层显示区域）
 */
typedef struct
{
  uint16_t x;        // 窗口起始X坐标
  uint16_t y;        // 窗口起始Y坐标
  uint16_t width;    // 窗口宽度
  uint16_t height;   // 窗口高度
} LCD_Window_t;

// ========================== 全局变量声明 ==========================
extern LCD_Layer_t currentLayer;          // 当前激活图层
extern uint16_t lcd_cursor_x;             // 光标X坐标
extern uint16_t lcd_cursor_y;             // 光标Y坐标
extern uint16_t lcd_fgColor;              // 前景色（RGB565）
extern uint16_t lcd_bgColor;              // 背景色（RGB565，0xFFFF为透明）
extern sFONT* lcd_font;                   // 当前字体指针
extern LCD_Window_t lcd_bg_window;        // 背景层窗口配置
extern LCD_Window_t lcd_fg_window;        // 前景层窗口配置

// ========================== 函数声明 ==========================
/**
 * @brief 初始化LCD底层驱动（DMA2D/LTDC）
 */
void BSP_LCD_Init(void);

/**
 * @brief 获取当前激活的LCD图层
 * @retval 当前激活图层（LCD_LAYER_BG/LCD_LAYER_FG）
 */
LCD_Layer_t BSP_LCD_GetActiveLayer(void);

/**
 * @brief 设置当前激活的LCD图层
 * @param layer 目标图层（LCD_LAYER_BG/LCD_LAYER_FG）
 */
void BSP_LCD_SetActiveLayer(LCD_Layer_t layer);

/**
 * @brief 获取指定图层的基地址
 * @param layer 目标图层（LCD_LAYER_BG/LCD_LAYER_FG）
 * @retval 图层的SDRAM基地址
 */
uint32_t BSP_LCD_GetLayerAddr(LCD_Layer_t layer);

/**
 * @brief 设置指定图层的显示窗口
 * @param layer 目标图层（LCD_LAYER_BG/LCD_LAYER_FG）
 * @param window 窗口配置结构体
 * @retval HAL状态（HAL_OK/HAL_ERROR）
 */
HAL_StatusTypeDef BSP_LCD_SetLayerWindow(LCD_Layer_t layer, LCD_Window_t window);

/**
 * @brief 获取指定图层的显示窗口配置
 * @param layer 目标图层（LCD_LAYER_BG/LCD_LAYER_FG）
 * @retval 窗口配置结构体
 */
LCD_Window_t BSP_LCD_GetLayerWindow(LCD_Layer_t layer);

/**
 * @brief 使用DMA2D填充指定区域
 * @param addr 填充起始地址（SDRAM地址）
 * @param width 填充宽度（像素）
 * @param height 填充高度（像素）
 * @param color 填充颜色（RGB565）
 * @retval HAL状态（HAL_OK/HAL_ERROR/HAL_TIMEOUT）
 */
HAL_StatusTypeDef BSP_LCD_DMA2D_Fill(uint32_t addr, uint16_t width, uint16_t height, uint16_t color);

/**
 * @brief 清空当前激活图层的显示窗口
 * @param color 填充颜色（RGB565）
 */
void BSP_LCD_ClearActiveLayer(uint16_t color);

/**
 * @brief 清空背景层全屏
 * @param color 填充颜色（RGB565）
 */
void BSP_LCD_FillBackground(uint16_t color);

/**
 * @brief 清空前景层全屏
 * @param color 填充颜色（RGB565）
 */
void BSP_LCD_FillForeground(uint16_t color);

/**
 * @brief 在当前激活图层绘制单个像素
 * @param x 像素X坐标
 * @param y 像素Y坐标
 * @param color 像素颜色（RGB565）
 */
void BSP_LCD_DrawPixel(uint16_t x, uint16_t y, uint16_t color);

/**
 * @brief 绘制直线（Bresenham算法）
 * @param x1 起点X坐标
 * @param y1 起点Y坐标
 * @param x2 终点X坐标
 * @param y2 终点Y坐标
 * @param color 直线颜色（RGB565）
 */
void BSP_LCD_DrawLine(uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, uint16_t color);

/**
 * @brief 绘制空心圆（中点圆算法）
 * @param x0 圆心X坐标
 * @param y0 圆心Y坐标
 * @param radius 圆半径
 * @param color 圆颜色（RGB565）
 */
void BSP_LCD_DrawCircle(uint16_t x0, uint16_t y0, uint16_t radius, uint16_t color);

/**
 * @brief 绘制实心圆
 * @param x0 圆心X坐标
 * @param y0 圆心Y坐标
 * @param radius 圆半径
 * @param color 圆颜色（RGB565）
 */
void BSP_LCD_FillCircle(uint16_t x0, uint16_t y0, uint16_t radius, uint16_t color);

/**
 * @brief 绘制空心矩形
 * @param x1 左上角X坐标
 * @param y1 左上角Y坐标
 * @param x2 右下角X坐标
 * @param y2 右下角Y坐标
 * @param color 矩形颜色（RGB565）
 */
void BSP_LCD_DrawRectangle(uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, uint16_t color);

/**
 * @brief 绘制实心矩形
 * @param x1 左上角X坐标
 * @param y1 左上角Y坐标
 * @param x2 右下角X坐标
 * @param y2 右下角Y坐标
 * @param color 矩形颜色（RGB565）
 */
void BSP_LCD_FillRectangle(uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, uint16_t color);

/**
 * @brief 在当前光标位置绘制单个字符
 * @param c 待绘制ASCII字符
 */
void BSP_LCD_DrawChar(char c);

/**
 * @brief 在当前激活图层绘制字符串（自动换行）
 * @param str 待绘制字符串指针
 */
void BSP_LCD_DrawString(const char* str);

/**
 * @brief 绘制十进制整数
 * @param num 待绘制32位有符号整数
 */
void BSP_LCD_DrawDec(int32_t num);

/**
 * @brief 绘制十六进制整数（自动带0x前缀）
 * @param num 待绘制32位无符号整数
 */
void BSP_LCD_DrawHex(uint32_t num);

/**
 * @brief 绘制浮点数（自动四舍五入）
 * @param fnum 待绘制浮点数
 * @param decimals 保留小数位数（0~15）
 */
void BSP_LCD_DrawFloat(float fnum, uint8_t decimals);

/**
 * @brief 格式化输出到LCD（类似printf）
 * @param fmt 格式化字符串
 * @param ... 可变参数列表
 */
void BSP_LCD_Printf(const char* fmt, ...);

/**
 * @brief LCD功能测试函数
 */
void BSP_LCD_Test(void);

// ========================== Setter/Getter 函数 ==========================
/**
 * @brief 设置光标坐标
 * @param x 光标X坐标
 * @param y 光标Y坐标
 */
void BSP_LCD_SetCursor(uint16_t x, uint16_t y);

/**
 * @brief 设置前景色
 * @param color 前景色（RGB565）
 */
void BSP_LCD_SetColor(uint16_t color);

/**
 * @brief 设置背景色
 * @param color 背景色（RGB565，0xFFFF为透明）
 */
void BSP_LCD_SetBgColor(uint16_t color);

/**
 * @brief 设置当前字体
 * @param font 字体指针（&Font8/&Font12/&Font16/&Font20/&Font24）
 */
void BSP_LCD_SetFont(sFONT* font);

#ifdef __cplusplus
}
#endif

#endif /* __BSP_LCD_H */